### ISSUE TITLE
Не удается установить плагин на RX версии 4.4 

### ISSUE THREAD

**Issue by ilda007** [DirectumCompany/rx-manage-applied-projects#15]
На тестовом стенде ОГВ, после обновления с 4.3 на версию 4.4, не удалось установить данную утилиту. При установке жалуется на отсутствие функции get_database_folder в файле dbtools.  В 4.4 нет данной функции, там идет уже разделение по движкам БД (mssql и psql).

**Comment by igel2000** [comment]
Исправлено
