### ISSUE TITLE
Сопутствующие видеоинструкции помимо рутуба заливать и на youtube

### ISSUE THREAD

**Issue by gureev** [DirectumCompany/rx-manage-applied-projects#16]
Рутуб не всегда работает стабильно, плюс раздражает обилие рекламы. В рамках импортозамещения деваться будет конечно некуда, но пока ютуб доступен - мб использовать его как альтернативу? Пусть по возможности ролики будут и там, и там.

**Comment by igel2000** [comment]
Уговорил )
