### ISSUE TITLE
Добавить поддержку разных СУБД для одной версии RX

### ISSUE THREAD

**Issue by NFanil** [DirectumCompany/rx-manage-applied-projects#20]
В текущей реализации в конфиге для проекта указывается только имя БД, а остальная часть строки подключения к БД и DATABASE_ENGINE указываются в конфиге в папке RX каждой версии.
Т.е. при необходимости использовать mssql и postgresql нужно будет создать разные папки одной версии RX. То же самое при необходимости использовать другой сервер БД.

Предлагаю в конфиге проекта указывать полную строку и DATABASE_ENGINE, чтобы не нужно было дублировать папку с RX нужной версии

**Comment by igel2000** [comment]
Пока могу предложить обходное решение.
1. Создать yml.файл, в котором определить переменные common_config->DATABASE_ENGINE и common_config->CONNECTION_STRING. Например
```
common_config: 
    DATABASE_ENGINE: 'postgres'
    CONNECTION_STRING: 'server=pgsrv;port=5432;database={{ database }};user id=user;Password=password'
```
2. Использовать команду `do map update_config` чтобы с помощью созданного yml-файла переключить инстанс на сервер pgsrv.
3. Переключить (`do map set`) инстанс на проект, который развернут на сервере pgsrv.

**Comment by igel2000** [comment]
`do map update_config` может добавлять и менять значения любых параметров в config.yml на основе указанного шаблона.

**Comment by NFanil** [comment]
спасибо
